name: sparse_matrix_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - cmake
  - ninja
  - make
  - clangxx
  - doxygen
  - libomp
  - pip
  - pip:
    - breathe
    - sphinx