name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

defaults:
  run:
    shell: bash -l {0}

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          # Latest supported versions
          - name: Linux
    steps:
    - name: Check out
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Show dependency file
      run: cat environment.yml
      
    - name: Install Mamba
      uses: mamba-org/setup-micromamba@v1
      with:
        environment-file: environment.yml
        cache-environment: false
        cache-downloads: true

    - name: List environment
      run: |
        micromamba activate cppdev
        micromamba list

    - name: Configure and compile the library
      run: |
        micromamba activate cppdev
        mkdir build && cd build
        cmake -DCMAKE_VERBOSE_MAKEFILE=yes -DCMAKE_INSTALL_PREFIX=$CONDA_PREFIX ..
        make -j6 all
                
    - name: Run tests
      run: |
        micromamba activate cppdev
        cd build
        ctest --output-on-failure 
                
